version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    environment:
      - Auth_Path=${Auth_Path}
      - User_Path=${User_Path}
      - Port=${Port}
    ports:
      - "${Port}:${Port}"
    depends_on:
      - user-service
      - auth-service
