version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - user-service
      - auth-service
    ports:
      - "8080:8080"
