server:
  port: ${Port}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${Auth_Path}
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: ${User_Path}
          predicates:
            - Path=/users/**
      default-filters:
        - AddResponseHeader=Cache-Control, no-cache, no-store, must-revalidate
        - AddResponseHeader=Pragma, no-cache
        - AddResponseHeader=Expires, 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    groups:
      enabled: true
  openapi:
    urls:
      - url: ${User_Path}/v3/api-docs
        name: User Service
      - url: ${Auth_Path}/v3/api-docs
        name: Auth Service
