version: '3.8'

services:
  auth-redis:
    image: redis:7.0
    container_name: auth-redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - UserServiceURL=${UserServiceURL}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    depends_on:
      - auth-redis
