# Base image
FROM openjdk:17-jdk-slim

# Working directory
WORKDIR /app

# Add jar file to the container
COPY build/libs/auth-service-0.0.1-SNAPSHOT.jar app.jar

# Expose application port
EXPOSE ${AUTH_SERVICE_PORT}

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
