version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USERPASSWORD}
      MYSQL_DATABASE: ${USERDB}
      MYSQL_USER: ${USERUSERNAME}
      MYSQL_PASSWORD: ${USERPASSWORD}
    ports:
      - "${DBPORT}:${DBPORT}"
    volumes:
      - db_data:/var/lib/mysql

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    environment:
      - USERHOST=${USERHOST}
      - USERDB=${USERDB}
      - USERUSERNAME=${USERUSERNAME}
      - USERPASSWORD=${USERPASSWORD}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - DBPORT=${DBPORT}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - db

volumes:
  db_data:
